// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, type Options as Options2, type RequestResult, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { CompleteSessionApiV1GameSessionsSessionIdCompletePostData, CompleteSessionApiV1GameSessionsSessionIdCompletePostErrors, CompleteSessionApiV1GameSessionsSessionIdCompletePostResponses, HealthHealthGetData, HealthHealthGetResponses, LoginApiV1AuthLoginPostData, LoginApiV1AuthLoginPostErrors, LoginApiV1AuthLoginPostResponses, ReadMeApiV1AuthMeGetData, ReadMeApiV1AuthMeGetResponses, ReadMyPointsLedgerApiV1WalletMeLedgerGetData, ReadMyPointsLedgerApiV1WalletMeLedgerGetErrors, ReadMyPointsLedgerApiV1WalletMeLedgerGetResponses, ReadMyWalletApiV1WalletMeGetData, ReadMyWalletApiV1WalletMeGetResponses, RegisterApiV1AuthRegisterPostData, RegisterApiV1AuthRegisterPostErrors, RegisterApiV1AuthRegisterPostResponses, RootGetData, RootGetResponses, StartSessionApiV1GameSessionsStartPostData, StartSessionApiV1GameSessionsStartPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Register
 */
export const registerApiV1AuthRegisterPost = <ThrowOnError extends boolean = false>(options: Options<RegisterApiV1AuthRegisterPostData, ThrowOnError>): RequestResult<RegisterApiV1AuthRegisterPostResponses, RegisterApiV1AuthRegisterPostErrors, ThrowOnError> => (options.client ?? client).post<RegisterApiV1AuthRegisterPostResponses, RegisterApiV1AuthRegisterPostErrors, ThrowOnError>({
    url: '/api/v1/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login
 */
export const loginApiV1AuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginApiV1AuthLoginPostData, ThrowOnError>): RequestResult<LoginApiV1AuthLoginPostResponses, LoginApiV1AuthLoginPostErrors, ThrowOnError> => (options.client ?? client).post<LoginApiV1AuthLoginPostResponses, LoginApiV1AuthLoginPostErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    url: '/api/v1/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * Read Me
 */
export const readMeApiV1AuthMeGet = <ThrowOnError extends boolean = false>(options?: Options<ReadMeApiV1AuthMeGetData, ThrowOnError>): RequestResult<ReadMeApiV1AuthMeGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ReadMeApiV1AuthMeGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/me',
    ...options
});

/**
 * Start Session
 */
export const startSessionApiV1GameSessionsStartPost = <ThrowOnError extends boolean = false>(options?: Options<StartSessionApiV1GameSessionsStartPostData, ThrowOnError>): RequestResult<StartSessionApiV1GameSessionsStartPostResponses, unknown, ThrowOnError> => (options?.client ?? client).post<StartSessionApiV1GameSessionsStartPostResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/game-sessions/start',
    ...options
});

/**
 * Complete Session
 */
export const completeSessionApiV1GameSessionsSessionIdCompletePost = <ThrowOnError extends boolean = false>(options: Options<CompleteSessionApiV1GameSessionsSessionIdCompletePostData, ThrowOnError>): RequestResult<CompleteSessionApiV1GameSessionsSessionIdCompletePostResponses, CompleteSessionApiV1GameSessionsSessionIdCompletePostErrors, ThrowOnError> => (options.client ?? client).post<CompleteSessionApiV1GameSessionsSessionIdCompletePostResponses, CompleteSessionApiV1GameSessionsSessionIdCompletePostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/game-sessions/{session_id}/complete',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read My Wallet
 */
export const readMyWalletApiV1WalletMeGet = <ThrowOnError extends boolean = false>(options?: Options<ReadMyWalletApiV1WalletMeGetData, ThrowOnError>): RequestResult<ReadMyWalletApiV1WalletMeGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ReadMyWalletApiV1WalletMeGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/wallet/me',
    ...options
});

/**
 * Read My Points Ledger
 */
export const readMyPointsLedgerApiV1WalletMeLedgerGet = <ThrowOnError extends boolean = false>(options?: Options<ReadMyPointsLedgerApiV1WalletMeLedgerGetData, ThrowOnError>): RequestResult<ReadMyPointsLedgerApiV1WalletMeLedgerGetResponses, ReadMyPointsLedgerApiV1WalletMeLedgerGetErrors, ThrowOnError> => (options?.client ?? client).get<ReadMyPointsLedgerApiV1WalletMeLedgerGetResponses, ReadMyPointsLedgerApiV1WalletMeLedgerGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/wallet/me/ledger',
    ...options
});

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>): RequestResult<RootGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>): RequestResult<HealthHealthGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });
