// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * Body_login_api_v1_auth_login_post
 */
export type BodyLoginApiV1AuthLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CompleteSessionRequest
 */
export type CompleteSessionRequest = {
    /**
     * Duration Seconds
     */
    duration_seconds: number;
    /**
     * Score
     */
    score: number;
};

/**
 * CompleteSessionResponse
 */
export type CompleteSessionResponse = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Score
     */
    score: number;
    /**
     * Base Points
     */
    base_points: number;
    /**
     * Awarded Points
     */
    awarded_points: number;
    /**
     * Wallet Balance
     */
    wallet_balance: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PointsLedgerEntryResponse
 */
export type PointsLedgerEntryResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Source Type
     */
    source_type: string;
    /**
     * Source Id
     */
    source_id: string | null;
    /**
     * Delta Points
     */
    delta_points: number;
    /**
     * Balance After
     */
    balance_after: number;
    /**
     * Idempotency Key
     */
    idempotency_key: string;
    /**
     * Reason
     */
    reason: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * RegisterRequest
 */
export type RegisterRequest = {
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Terms Version
     */
    terms_version: string;
    /**
     * Promo Consent
     */
    promo_consent?: boolean;
};

/**
 * StartSessionResponse
 */
export type StartSessionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Started At
     */
    started_at: string;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Role
     */
    role: string;
    /**
     * Status
     */
    status: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WalletResponse
 */
export type WalletResponse = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Available Points
     */
    available_points: number;
    /**
     * Lifetime Earned Points
     */
    lifetime_earned_points: number;
    /**
     * Lifetime Spent Points
     */
    lifetime_spent_points: number;
    /**
     * Updated At
     */
    updated_at: string;
};

export type RegisterApiV1AuthRegisterPostData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterApiV1AuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiV1AuthRegisterPostError = RegisterApiV1AuthRegisterPostErrors[keyof RegisterApiV1AuthRegisterPostErrors];

export type RegisterApiV1AuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: UserResponse;
};

export type RegisterApiV1AuthRegisterPostResponse = RegisterApiV1AuthRegisterPostResponses[keyof RegisterApiV1AuthRegisterPostResponses];

export type LoginApiV1AuthLoginPostData = {
    body: BodyLoginApiV1AuthLoginPost;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type ReadMeApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type ReadMeApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type ReadMeApiV1AuthMeGetResponse = ReadMeApiV1AuthMeGetResponses[keyof ReadMeApiV1AuthMeGetResponses];

export type StartSessionApiV1GameSessionsStartPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/game-sessions/start';
};

export type StartSessionApiV1GameSessionsStartPostResponses = {
    /**
     * Successful Response
     */
    201: StartSessionResponse;
};

export type StartSessionApiV1GameSessionsStartPostResponse = StartSessionApiV1GameSessionsStartPostResponses[keyof StartSessionApiV1GameSessionsStartPostResponses];

export type CompleteSessionApiV1GameSessionsSessionIdCompletePostData = {
    body: CompleteSessionRequest;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/game-sessions/{session_id}/complete';
};

export type CompleteSessionApiV1GameSessionsSessionIdCompletePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompleteSessionApiV1GameSessionsSessionIdCompletePostError = CompleteSessionApiV1GameSessionsSessionIdCompletePostErrors[keyof CompleteSessionApiV1GameSessionsSessionIdCompletePostErrors];

export type CompleteSessionApiV1GameSessionsSessionIdCompletePostResponses = {
    /**
     * Successful Response
     */
    200: CompleteSessionResponse;
};

export type CompleteSessionApiV1GameSessionsSessionIdCompletePostResponse = CompleteSessionApiV1GameSessionsSessionIdCompletePostResponses[keyof CompleteSessionApiV1GameSessionsSessionIdCompletePostResponses];

export type ReadMyWalletApiV1WalletMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/wallet/me';
};

export type ReadMyWalletApiV1WalletMeGetResponses = {
    /**
     * Successful Response
     */
    200: WalletResponse;
};

export type ReadMyWalletApiV1WalletMeGetResponse = ReadMyWalletApiV1WalletMeGetResponses[keyof ReadMyWalletApiV1WalletMeGetResponses];

export type ReadMyPointsLedgerApiV1WalletMeLedgerGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/wallet/me/ledger';
};

export type ReadMyPointsLedgerApiV1WalletMeLedgerGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadMyPointsLedgerApiV1WalletMeLedgerGetError = ReadMyPointsLedgerApiV1WalletMeLedgerGetErrors[keyof ReadMyPointsLedgerApiV1WalletMeLedgerGetErrors];

export type ReadMyPointsLedgerApiV1WalletMeLedgerGetResponses = {
    /**
     * Response Read My Points Ledger Api V1 Wallet Me Ledger Get
     *
     * Successful Response
     */
    200: Array<PointsLedgerEntryResponse>;
};

export type ReadMyPointsLedgerApiV1WalletMeLedgerGetResponse = ReadMyPointsLedgerApiV1WalletMeLedgerGetResponses[keyof ReadMyPointsLedgerApiV1WalletMeLedgerGetResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
